"use client";

import { useMemo, useState } from "react";

type Page = "home" | "books" | "categories";
type ViewMode = "grid" | "list";
type Book = { id:number; title:string; author:string; category:string; format:string; status:"未読"|"読書中"|"読了"; date:string; cover:string; short:string };

const books:Book[] = [
  {id:1,title:"プロジェクトマネジメントの本物の実力がつく本",author:"橋本 将功",category:"エンジニア論",format:"単行本",status:"未読",date:"2026-08-16",cover:"navy",short:"PROJECT\nMANAGEMENT"},
  {id:2,title:"プロジェクトマネジメントの基本が全部わかる本",author:"橋本 将功",category:"エンジニア論",format:"単行本",status:"未読",date:"2026-08-16",cover:"ivory",short:"PROJECT\nMANAGEMENT"},
  {id:3,title:"システム開発と「具体と抽象」",author:"細谷 功",category:"技術書",format:"単行本",status:"読了",date:"2026-08-09",cover:"gray",short:"具体\nと\n抽象"},
  {id:4,title:"システムの引き継ぎに失敗しないための本",author:"黒渕 由幸",category:"技術書",format:"単行本",status:"読書中",date:"2026-08-06",cover:"teal",short:"引き継ぎに\n失敗しない"},
  {id:5,title:"バイブコーディングを超えて",author:"Addy Osmani",category:"AI",format:"単行本",status:"未読",date:"2026-08-02",cover:"bird",short:"VIBE\nCODING"},
  {id:6,title:"AWSではじめるMCP実践ガイド",author:"山田 太郎",category:"クラウド",format:"単行本",status:"未読",date:"2026-07-28",cover:"pink",short:"AWS × MCP\n実践ガイド"},
  {id:7,title:"本質を捉えたデータ分析のための分析モデル入門",author:"杉山 聡",category:"データサイエンス",format:"単行本",status:"読書中",date:"2026-07-20",cover:"blue",short:"分析\nモデル"},
  {id:8,title:"パーソナルデータの教科書",author:"佐藤 一郎",category:"データサイエンス",format:"電子書籍",status:"読了",date:"2026-07-12",cover:"yellow",short:"PERSONAL\nDATA"},
];

const categoryData = [["技術書","Technical",32],["小説","Novel",8],["ビジネス","Business",21],["デザイン","Design",12],["歴史","History",9],["統計","Statistics",14],["AI","AI",18],["クラウド","Cloud",11],["データサイエンス","Data Science",19]] as const;

function BookCover({book,compact=false}:{book:Book;compact?:boolean}) { return <div className={`book-cover cover-${book.cover} ${compact?"compact":""}`} aria-label={`${book.title}の書影`}><span className="cover-kicker">ISBN LIBRARY</span><strong>{book.short.split("\n").map(line=><span key={line}>{line}</span>)}</strong><small>{book.author}</small></div> }
function Status({value}:{value:Book["status"]}) { return <span className={`status status-${value}`}>{value}</span> }
function NavButton({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}) { return <button className={active?"active":""} onClick={onClick}>{children}</button> }
function MobileNav({active,icon,label,onClick,primary=false}:{active:boolean;icon:string;label:string;onClick:()=>void;primary?:boolean}) { return <button className={`${active?"active":""} ${primary?"primary":""}`} onClick={onClick}><span>{icon}</span><small>{label}</small></button> }

export default function Home() {
  const [page,setPage]=useState<Page>("home"), [query,setQuery]=useState(""), [status,setStatus]=useState("すべて"), [category,setCategory]=useState("すべて"), [sort,setSort]=useState("登録日が新しい順"), [filterOpen,setFilterOpen]=useState(false), [view,setView]=useState<ViewMode>("grid"), [selected,setSelected]=useState<Book|null>(null), [categoryEdit,setCategoryEdit]=useState<(typeof categoryData)[number]|null>(null), [toast,setToast]=useState("");
  const filteredBooks=useMemo(()=>{const q=query.toLowerCase();return books.filter(b=>(!q||`${b.title}${b.author}`.toLowerCase().includes(q))&&(status==="すべて"||b.status===status)&&(category==="すべて"||b.category===category))},[query,status,category]);
  function navigate(next:Page){setPage(next);window.scrollTo({top:0,behavior:"smooth"})}
  function notify(message:string){setToast(message);window.setTimeout(()=>setToast(""),2600)}
  const pageMeta={home:["ホーム","Chasosoさんの蔵書ダッシュボード"],books:["蔵書一覧","読みたい本に、すぐ出会える本棚"],categories:["カテゴリ管理","蔵書の分類をシンプルに整える"]}[page];
  return <main className="app-shell">
    <header className="site-header"><div className="header-inner"><button className="brand" onClick={()=>navigate("home")} aria-label="ホームへ"><span className="brand-mark">I</span><span>ISBN LIBRARY</span></button><nav className="desktop-nav" aria-label="メインナビゲーション"><NavButton active={page==="home"} onClick={()=>navigate("home")}>ホーム</NavButton><NavButton active={page==="books"} onClick={()=>navigate("books")}>蔵書一覧</NavButton><NavButton active={page==="categories"} onClick={()=>navigate("categories")}>カテゴリ管理</NavButton><button className="avatar" onClick={()=>notify("ユーザーメニューを開きます")} aria-label="ユーザーメニュー">CY</button></nav><button className="mobile-more" onClick={()=>notify("ユーザーメニューを開きます")} aria-label="ユーザーメニュー">•••</button></div></header>
    <div className="page-wrap"><div className="page-heading"><p className="eyebrow">MY BOOKSHELF</p><h1>{pageMeta[0]}</h1><p>{pageMeta[1]}</p></div>
      {page==="home"&&<HomePage navigate={navigate} setSelected={setSelected} query={query} setQuery={setQuery}/>} 
      {page==="books"&&<BooksPage books={filteredBooks} query={query} setQuery={setQuery} status={status} setStatus={setStatus} category={category} setCategory={setCategory} sort={sort} setSort={setSort} view={view} setView={setView} openFilters={()=>setFilterOpen(true)} setSelected={setSelected}/>} 
      {page==="categories"&&<CategoriesPage onEdit={setCategoryEdit} onAdd={()=>setCategoryEdit(["","",0])}/>} 
    </div>
    <button className="scan-fab" onClick={()=>notify("カメラを起動してISBNをスキャンします")}><span>⌗</span><b>スキャン</b></button>
    <nav className="mobile-nav" aria-label="モバイルナビゲーション"><MobileNav active={page==="home"} icon="⌂" label="ホーム" onClick={()=>navigate("home")}/><MobileNav active={page==="books"} icon="▤" label="蔵書" onClick={()=>navigate("books")}/><MobileNav active={false} icon="⌗" label="スキャン" primary onClick={()=>notify("カメラを起動してISBNをスキャンします")}/><MobileNav active={page==="categories"} icon="◫" label="分類" onClick={()=>navigate("categories")}/></nav>
    {filterOpen&&<div className="modal-backdrop" onMouseDown={()=>setFilterOpen(false)}><section className="filter-sheet" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-labelledby="filter-title"><div className="sheet-handle"/><div className="sheet-heading"><h2 id="filter-title">絞り込み・並び替え</h2><button onClick={()=>setFilterOpen(false)} aria-label="閉じる">×</button></div><FilterFields status={status} setStatus={setStatus} category={category} setCategory={setCategory} sort={sort} setSort={setSort}/><div className="sheet-actions"><button className="ghost-button" onClick={()=>{setStatus("すべて");setCategory("すべて")}}>リセット</button><button className="primary-button" onClick={()=>setFilterOpen(false)}>{filteredBooks.length}冊を表示</button></div></section></div>}
    {selected&&<div className="modal-backdrop" onMouseDown={()=>setSelected(null)}><section className="book-dialog" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-labelledby="book-title"><button className="dialog-close" onClick={()=>setSelected(null)} aria-label="閉じる">×</button><BookCover book={selected}/><div className="dialog-copy"><p className="eyebrow">BOOK DETAILS</p><h2 id="book-title">{selected.title}</h2><p className="author">{selected.author}</p><div className="tag-row"><Status value={selected.status}/><span className="tag">{selected.category}</span><span className="tag">{selected.format}</span></div><p className="dialog-note">読書メモやステータスを確認・更新できます。このプロトタイプでは画面遷移と情報の優先順位を確認できます。</p><button className="primary-button" onClick={()=>notify("書籍の編集画面を開きます")}>この本を編集</button></div></section></div>}
    {categoryEdit&&<div className="modal-backdrop" onMouseDown={()=>setCategoryEdit(null)}><section className="edit-sheet" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-labelledby="edit-title"><div className="sheet-handle"/><div className="sheet-heading"><h2 id="edit-title">{categoryEdit[0]?"カテゴリを編集":"カテゴリを追加"}</h2><button onClick={()=>setCategoryEdit(null)}>×</button></div><label>日本語名<input defaultValue={categoryEdit[0]} placeholder="例：技術書"/></label><label>英語名<input defaultValue={categoryEdit[1]} placeholder="例：Technical"/></label><button className="primary-button full" onClick={()=>{setCategoryEdit(null);notify("カテゴリを保存しました")}}>保存する</button></section></div>}
    {toast&&<div className="toast" role="status">{toast}</div>}
  </main>
}

function HomePage({navigate,setSelected,query,setQuery}:{navigate:(p:Page)=>void;setSelected:(b:Book)=>void;query:string;setQuery:(q:string)=>void}) { return <>
  <section className="overview-card"><div><p className="eyebrow inverse">YOUR BOOKSHELF</p><h2>本棚の状態を、ひと目で</h2><p>次に読む本も、最近の読書も。144冊の中から迷わず見つけられます。</p></div><div className="stat-grid"><button onClick={()=>navigate("books")}><strong>144</strong><span>すべての本</span></button><button className="light" onClick={()=>navigate("books")}><strong>53</strong><span>未読の本</span></button><button className="mobile-only-stat" onClick={()=>setSelected(books[3])}><strong>2</strong><span>読書中</span></button></div></section>
  <section className="search-panel"><div><p className="eyebrow">SEARCH</p><h2>次に読みたい1冊を探す</h2></div><div className="search-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="タイトル・著者で検索" aria-label="タイトル・著者で検索"/><button onClick={()=>navigate("books")}>検索</button></div></section>
  <section className="reading-now"><div className="section-title"><div><p className="eyebrow">CURRENTLY READING</p><h2>いま読んでいる本</h2></div><button onClick={()=>setSelected(books[3])}>詳細を見る →</button></div><button className="current-book" onClick={()=>setSelected(books[3])}><BookCover book={books[3]} compact/><div><Status value="読書中"/><h3>{books[3].title}</h3><p>{books[3].author}</p><div className="progress"><span style={{width:"62%"}}/></div><small>62% 読了</small></div></button></section>
  <section className="recent-section"><div className="section-title"><div><p className="eyebrow">RECENTLY ADDED</p><h2>新しく棚に並んだ本</h2></div><button onClick={()=>navigate("books")}>すべて見る →</button></div><div className="book-grid home-grid">{books.slice(0,4).map(book=><BookCard key={book.id} book={book} onClick={()=>setSelected(book)}/>)}</div></section>
  </> }

type BooksProps={books:Book[];query:string;setQuery:(v:string)=>void;status:string;setStatus:(v:string)=>void;category:string;setCategory:(v:string)=>void;sort:string;setSort:(v:string)=>void;view:ViewMode;setView:(v:ViewMode)=>void;openFilters:()=>void;setSelected:(b:Book)=>void};
function BooksPage(props:BooksProps) { const chips=[props.status!=="すべて"?props.status:"",props.category!=="すべて"?props.category:""].filter(Boolean); return <>
  <section className="library-tools"><div className="search-box"><span>⌕</span><input value={props.query} onChange={e=>props.setQuery(e.target.value)} placeholder="タイトル・著者で検索" aria-label="タイトル・著者で検索"/><button>検索</button></div><div className="desktop-filters"><FilterFields {...props}/></div><div className="mobile-tool-row"><button className="filter-button" onClick={props.openFilters}>☷ 絞り込み・並び替え{chips.length>0&&<b>{chips.length}</b>}</button><div className="view-toggle"><button className={props.view==="grid"?"active":""} onClick={()=>props.setView("grid")} aria-label="グリッド表示">▦</button><button className={props.view==="list"?"active":""} onClick={()=>props.setView("list")} aria-label="リスト表示">☷</button></div></div>{chips.length>0&&<div className="active-chips">{chips.map(chip=><span key={chip}>{chip}</span>)}<button onClick={()=>{props.setStatus("すべて");props.setCategory("すべて")}}>条件をクリア</button></div>}</section>
  <section className="results-section"><div className="results-heading"><p><strong>{props.books.length}</strong>冊の本</p><div className="desktop-view-toggle view-toggle"><button className={props.view==="grid"?"active":""} onClick={()=>props.setView("grid")}>▦ グリッド</button><button className={props.view==="list"?"active":""} onClick={()=>props.setView("list")}>☷ リスト</button></div></div><div className={`book-grid ${props.view==="list"?"list-view":""}`}>{props.books.map(book=><BookCard key={book.id} book={book} onClick={()=>props.setSelected(book)} list={props.view==="list"}/>)}</div>{props.books.length===0&&<div className="empty-state"><span>⌕</span><h3>本が見つかりませんでした</h3><p>検索語や絞り込み条件を変更してください。</p></div>}</section>
  </> }

function FilterFields({status,setStatus,category,setCategory,sort,setSort}:{status:string;setStatus:(v:string)=>void;category:string;setCategory:(v:string)=>void;sort:string;setSort:(v:string)=>void}) { return <div className="filter-fields"><label>並び替え<select value={sort} onChange={e=>setSort(e.target.value)}><option>登録日が新しい順</option><option>タイトル順</option><option>著者名順</option></select></label><label>カテゴリ<select value={category} onChange={e=>setCategory(e.target.value)}><option>すべて</option><option>技術書</option><option>エンジニア論</option><option>AI</option><option>クラウド</option><option>データサイエンス</option></select></label><label>読書ステータス<select value={status} onChange={e=>setStatus(e.target.value)}><option>すべて</option><option>未読</option><option>読書中</option><option>読了</option></select></label></div> }
function BookCard({book,onClick,list=false}:{book:Book;onClick:()=>void;list?:boolean}) { return <button className={`book-card ${list?"book-card-list":""}`} onClick={onClick}><BookCover book={book} compact={list}/><div className="book-copy"><div className="tag-row"><Status value={book.status}/><span className="tag">{book.category}</span></div><h3>{book.title}</h3><p>{book.author}</p><small>{book.date}</small></div><span className="card-arrow">→</span></button> }
function CategoriesPage({onEdit,onAdd}:{onEdit:(c:(typeof categoryData)[number])=>void;onAdd:()=>void}) { const [search,setSearch]=useState("");const filtered=categoryData.filter(c=>`${c[0]}${c[1]}`.toLowerCase().includes(search.toLowerCase()));return <section className="categories-panel"><div className="category-toolbar"><div><p className="eyebrow">CATEGORY LIST</p><h2>カテゴリを整理する</h2></div><button className="primary-button" onClick={onAdd}>＋ カテゴリを追加</button></div><div className="category-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="カテゴリを検索"/></div><div className="category-table"><div className="category-table-head"><span>カテゴリ名</span><span>登録冊数</span><span>操作</span></div>{filtered.map(c=><div className="category-row" key={c[0]}><div><strong>{c[0]}</strong><small>{c[1]}</small></div><span className="book-count">{c[2]}冊</span><button onClick={()=>onEdit(c)} aria-label={`${c[0]}を編集`}>•••</button></div>)}</div></section> }
